[[main]]
  name = "GitHub"
  url = "https://naughty-noyce-750f53.netlify.app/"
  weight = 10

[[social]]
  name = "LinkedIn"
  url = "https://naughty-noyce-750f53.netlify.app/"
  weight = 20

[[social]]
  name = "Twitter"
  url = "https://naughty-noyce-750f53.netlify.app/"
  weight = 30
